### ISSUE TITLE
HackyHour[5] on 2016-03-30

### ISSUE THREAD

**Issue by nterhoeven** [HackyHour/Wuerzburg#15]
Ideas for this months HackyHour:
- setting up email encryption using PGP

**Comment by iimog** [comment]
Talking about encryption and gpg sounds like a good plan.
We can also continue our Raspberry experiments...

**Comment by EzioAuditoredaFirenze** [comment]
Agree with @iimog. A demo on secure generation of PGP keys and the basics of encryption would be nice. Since we didn't have time to set up an OwnCloud server during the last meeting, it would be great to do it this time. :)

**Comment by lleiding** [comment]
I vote in favour of gpg. Maybe we could talk a bit about strategies of managing keys across several devices. Also +1 (raspy) file server.

**Comment by greatfireball** [comment]
RAID and ZFS are still open :)
