### ISSUE TITLE
HackyHour[6] on 2016-05-04 (rescheduled)

### ISSUE THREAD

**Issue by iimog** [HackyHour/Wuerzburg#16]
Let's discuss topics for this months HackyHour.
I would be interested in checking out Coding Dojos.
What do you think? Other suggestions?

**Comment by nterhoeven** [comment]
What are Coding Dojos?

**Comment by iimog** [comment]
Look here to get a rough idea:
http://codingdojo.org/

**Comment by EzioAuditoredaFirenze** [comment]
Coding Dojos sounds like a great idea. I'm not really good at coding, so if you could mention the programming language that we would use to code, I could read a bit and come prepared. :wink:

**Comment by iimog** [comment]
@EzioAuditoredaFirenze I'd suggest using [python](https://www.python.org/). It is one of the most popular languages at the moment. It is also said to be suitable for beginners. Furthermore others (including myself, @nterhoeven and @greatfireball) do not use python, yet. So we would all start with little prior knowledge.

**Comment by iimog** [comment]
**There is a suggestion in the [gitter channel](https://gitter.im/HackyHour/Wuerzburg) to reschedule the next HackyHour to the 4th of May due to a conflict with the GSLS general assembly. Please comment via gitter if you do not want to reschedule.**

**Comment by iimog** [comment]
**HackyHour[6] will take place on the 4th of May at 6pm in the CCTB**

**Comment by iimog** [comment]
I have another suggestion :smiling_imp: 
How about a little poker after the HackyHour?
We can switch over to poker at 8pm so it wont get too late.

**Comment by iimog** [comment]
We successfully solved "The Descent" and "Mars Lander Level 1" on [codingame.com](https://codingame.com) in coding dojo fashion. It was a lot of fun. We solved "Skynet: the Chasm" only partially. Everyone is welcome to finish it off and present their solution in the next HackyHour #18
