### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by iimog** [HackyHour/Wuerzburg#17]
It would be nice to have a logo. Something that can be used to refer to HackyHour and as avatar for the GitHub organization. It can be very simple as long as it is recognizable. Any suggestions are welcome.

**Comment by iimog** [comment]
First suggestion using opencliparts:
- [clock background](https://openclipart.org/detail/232705/clock-background)
- [baby tux](https://openclipart.org/detail/23387/baby-tux)
  ![logo](https://cloud.githubusercontent.com/assets/7403236/14702531/3e1d7300-07ab-11e6-9503-fcff0d3682c2.png)
  Although the parts of the logo are in the public domain Tux might be protected as a trademark or something. Does anybody know?

**Comment by iimog** [comment]
The icon of HackyHour Auckland is also very nice:
https://uoa-eresearch.github.io/HackyHour/img/hacky.png

**Comment by EzioAuditoredaFirenze** [comment]
Just a rough sketch of my idea to represent **H**acky **H**our **Wü**rzburg.
![hhwu](https://cloud.githubusercontent.com/assets/14791703/14785374/bb615ca8-0afa-11e6-8745-098efde1d662.png)

**Comment by iimog** [comment]
![Image](https://cdn.rawgit.com/HackyHour/Wuerzburg/master/logo/logo_suggestion_07_2016.svg)

This is another suggestion. Comments are very welcome.

**Comment by phryneas** [comment]
The glorious triple-butt.

**Comment by greatfireball** [comment]
We need to fix the issue with the font, but I prefer the last suggestion :D

**Comment by iimog** [comment]
What are your opinions about contacting the Auckland people. As we already use the same name - maybe they'd agree that we can use their logo (maybe with Wü in it). So we can build a global brand :smile:

**Comment by cameronmclean** [comment]
Hi HackyHour Würzburg! Cam here from Auckland. You are most welcome to use and adapt the hackyhour name and logo we have. The logo is in fact in the public domain :) https://thenounproject.com/search/?q=hackathon&i=6324  
Really great to see another HackyHour spring up. We run our sessions in Auckland pretty informally. Some weeks are busy, others not, but do keep going with it - it's a really valuable contribution to intellectual culture on campus.

**Comment by iimog** [comment]
@cameronmclean, thanks a lot. This is wonderful. I really enjoyed the meet-ups we had so far. In case you ever come anywhere close to Würzburg - let us know and we'll have a special HackyHour :smiley:

@all I'd strongly vote to adopt the nice HackyHour Auckland logo. Feel free to put your "+1" or "-1" as reaction to this comment.

**Comment by iimog** [comment]
So here are two suggestions feel free to complain or make your own suggestion:
- Update 1: converted font to path - the one we used is likely not available on all systems
- Update 2: fonts still not showing correctly as images are cached by github
- Update 3: also not working, sorry - deleted the new comment again
- Update 4: tricked caching by changing raw.git.com to rawgithub.com - now the font is fixed
  I'll try it with a new comment.

This is the daytime logo 1pm:
![Image](https://rawgithub.com/HackyHour/Wuerzburg/master/logo/hackyhour_wue.svg)
This is the nighttime logo 1am:
![Image](https://rawgithub.com/HackyHour/Wuerzburg/master/logo/hackyhour_wue_inverse.svg)

**Comment by greatfireball** [comment]
Warum zwei :D

**Comment by iimog** [comment]
This is the daytime logo 1pm:
![Image](https://cdn.rawgit.com/HackyHour/Wuerzburg/master/logo/hackyhour_wue.svg)
This is the nighttime logo 1am:
![Image](https://cdn.rawgit.com/HackyHour/Wuerzburg/master/logo/hackyhour_wue_inverse.svg)

**Comment by iimog** [comment]
I fixed the font in the logos above. @greatfireball maybe you want to reconsider your confused emoji - in case it was because of the font...

**Comment by nterhoeven** [comment]
The light one is easier to understand from a distance/as a small logo. I am voting for this version

**Comment by iimog** [comment]
We have a logo :smiley:
