### ISSUE TITLE
General date for future HackyHours

### ISSUE THREAD

**Issue by iimog** [HackyHour/Wuerzburg#19]
There is at least one person out there, who wants to participate in the HackyHour but can not make it on Wednesdays. Therefore I open this thread to discuss the date of future HackyHours. I will add comments for Monday, Tuesday, Wednesday and Thursday. Everyone can give an upvote or a downvote to each of the comments. You can give neither if it is ok but not perfect. It will still be in the last week of the month and still at 6pm in the CCTB. If you want to discuss the week, time or place feel free to open another issue.

The weekday with the best up-vote/total-vote ratio on the 16th of May will be our date for the next months :smiley:

**Comment by iimog** [comment]
Monday

**Comment by iimog** [comment]
Tuesday

**Comment by iimog** [comment]
Wednesday

**Comment by iimog** [comment]
Thursday

**Comment by greatfireball** [comment]
What about FRIDAY!

**Comment by greatfireball** [comment]
Saturday

**Comment by greatfireball** [comment]
Sunday

**Comment by iimog** [comment]
This poll is now closed. With 4 up-votes and 0 down-votes Thursday will be our new weekday for future HackyHours. As the last Thursday of May is holiday we will meet on June, 2nd.
